### ISSUE TITLE
Efficient pipeline processing

### ISSUE THREAD

**Issue by joarobles** [thescalaguy/detectpii#2]
Right now each `Scanner` instance iterates through all columns in the data source, and this is done for every scanner in the pipeline.

This could be improved if the pipeline is in charge of iterating through columns and then applying all scanners to the n-th column.

I can create a pull request if you agree.

**Comment by thescalaguy** [comment]
Hey @joarobles,

All `Scanner`s work differently. All that is required of each `Scanner` is that they rely on the `Catalog` to fetch the information needed to perform the scan ([see here](https://github.com/thescalaguy/detectpii/blob/5cb488f67c2c0063483c58ea728cc769d2423231/detectpii/model.py#L52)). This allows each `Scanner` to encapsulate its own logic to perform a scan.

At the start of every run, the `Catalog` fetches the information about which tables are present in the data source, along with the columns for each ([see here](https://github.com/thescalaguy/detectpii/blob/5cb488f67c2c0063483c58ea728cc769d2423231/detectpii/pipeline/pii_detection.py#L16)). This information is cached. Every scanner is then passed this catalog to perform PII scans ([see here](https://github.com/thescalaguy/detectpii/blob/5cb488f67c2c0063483c58ea728cc769d2423231/detectpii/pipeline/pii_detection.py#L20)).  

If there are multiple `MetadataScanner`s in the pipeline, they’ll reuse this information without accessing the data source again.  

In contrast, a `DataScanner` requires a sample of rows which it fetches using the `Catalog` ([see here](https://github.com/thescalaguy/detectpii/blob/5cb488f67c2c0063483c58ea728cc769d2423231/detectpii/scanner/data.py#L26)). By design, the sample is fetched row-by-row to reduce the amount of memory it takes to run a scan. The drawback  is that if there are multiple `DataScanner`s, they’ll refetch the samples.   

This is why the pipeline passes the catalog to each scanner in turn and lets the scanner perform its own iteration.  

Does this answer the question?

**Comment by joarobles** [comment]
Thanks @thescalaguy for your reply, 

I understand your design and having the `Catalog` cached is a huge improvement to prevent querying the information schema multiple times. 

My concern was that every scanner has two nested for-loops, that could be handled in the pipeline level since all of them should iterate over all columns, this could also help `DataScanner` instances to reuse existing data samples.

What do you think?

**Comment by thescalaguy** [comment]
Hey @joarobles,

I believe the following code snippet is the approach you’re outlining to avoid having to iterate over rows and columns multiple times in every scanner. 

```python
for table in self.catalog.tables:
    
    sample = self.catalog.sample(table, percentage)

    for row in sample:
        for column, value in row:
            for scanner in self.scanners:
                pii_type: PiiType | None = scanner.scan(column=column, value=str(value))

                if pii_type:
                    pii_columns.append(...)
```    

Would this be a proper understanding of what you’re proposing?

**Comment by thescalaguy** [comment]
Hey @joarobles,

I’ve raised PR #6 which moves iteration over rows out of the scanners and into the pipeline.
